### PR TITLE
fix: implement bar function

### LINKED ISSUE #2: Implement bar function

### PR DESCRIPTION
**Pull request by dmkonq**
resolves #2

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -7,7 +7,7 @@ func foo() (string, error) {
 }
 
 func bar() (string, error) {
-	return "", errors.New("not implemented")
+	return "bar", nil
```
Comment (crowdigit) [inline main.go:11]: asdfjklasdfkjdkjskldl

**Review by crowdigit — CHANGES_REQUESTED** [review]
Fixasdfasdf

**Review by crowdigit — APPROVED** [review]
